export const videos = [
  {
    id: "1a2b3c4d5e6f7g8h9i10",
    title: "How Reverse Proxies Work",
    description: "Learn how to configure an nginx reverse proxy server.",
    tags: ["devops", "proxies"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/wE3b6WAPt5U?si=Ks7NUqiNXA2P04iD",
      github: "https://www.github.com",
      coverphoto: "/blogs/c-d-x-PDX_a_82obo-unspla.jpg",
    },
    metadata: {
      likes: 234,
      comments: 28,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `In this tutorial, you'll learn how to set up and configure a reverse proxy 
          using Nginx to improve web performance and security.`,
      keypoints: [
        "What is a reverse proxy.",
        "How reverse proxies enhance security.",
        "Setting up Nginx as a reverse proxy.",
        "Configuration tips for load balancing.",
        "Best practices for HTTPS setup.",
      ],
      features: [
        "Secure your web application.",
        "Load balancing for better performance.",
        "Easy Nginx configuration steps.",
        "HTTP to HTTPS redirection.",
        "Supports WebSocket protocols.",
      ],
      libraries: ["Nginx", "LetsEncrypt", "OpenSSL"],
      resources: ["Official Nginx documentation", "Let's Encrypt guide"],
      transcript: `answer `,
    },
  },
  {
    id: "11aa22bb33cc44dd55ee",
    title: "Introduction to Docker",
    description: "Master the basics of Docker for containerization.",
    tags: ["docker", "devops"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/X48VuDVv0do?si=Jqb4QFjtJqIGRoYe",
      github: "https://www.github.com",
      coverphoto: "/blogs/carlos-muza-hpjSkU2UYSU-unsplash.jpg",
    },
    metadata: {
      likes: 120,
      comments: 15,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `This guide introduces you to Docker, an essential tool for containerized 
          application development.`,
      keypoints: [
        "What is Docker?",
        "Building Docker images.",
        "Managing containers.",
        "Using Docker Compose for multi-container apps.",
        "Best practices in Dockerfile creation.",
      ],
      features: [
        "Scalable containerized apps.",
        "Simplifies deployment.",
        "Efficient resource usage.",
      ],
      libraries: ["Docker CLI", "Docker Compose"],
      resources: ["Docker documentation", "Play with Docker"],
      transcript: ``,
    },
  },
  {
    id: "abc123xyz456def789ghi",
    title: "Getting Started with React",
    description: "A beginner's guide to React.js.",
    tags: ["frontend", "react"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/t8pPdKYpowI?si=lwZ8hnv6LwTU2Zzn",
      github: "https://www.github.com",
      coverphoto: "/blogs/christina-wocintechchat-com-OtHEYbQXLFU-unspla.jpg",
    },
    metadata: {
      likes: 300,
      comments: 45,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `Dive into the fundamentals of React.js and build interactive user interfaces.`,
      keypoints: [
        "Understanding components.",
        "Managing state and props.",
        "React hooks basics.",
        "Routing with React Router.",
      ],
      features: [
        "Interactive UIs.",
        "Reusable components.",
        "Single-page applications.",
      ],
      libraries: ["React", "React Router"],
      resources: ["React documentation", "Create React App guide"],
      transcript: ``,
    },
  },
  {
    id: "12b34c56d78e90f12g34",
    title: "Building APIs with Express.js",
    description: "Create powerful RESTful APIs using Express.js.",
    tags: ["backend", "nodejs"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/3c-iBn73dDE?si=hyjC_GBycsCTKTH1",
      github: "https://www.github.com",
      coverphoto: "/blogs/emile-perron-xrVDYZRGdw4-unsplash.jpg",
    },
    metadata: {
      likes: 210,
      comments: 18,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `Learn how to develop RESTful APIs with Express.js, a minimalist framework for Node.js.`,
      keypoints: [
        "Setting up Express.js.",
        "Routing and middleware.",
        "Building a CRUD API.",
        "Error handling and validation.",
      ],
      features: [
        "Fast API development.",
        "Middleware support.",
        "Integration with databases.",
      ],
      libraries: ["Express", "Body-parser", "Cors"],
      resources: ["Express.js documentation", "Postman for API testing"],
      transcript: ``,
    },
  },
  {
    id: "a1b2c3d4e5f6g7h8i9j0",
    title: "Intro to Kubernetes",
    description: "Understand Kubernetes and its core concepts.",
    tags: ["kubernetes", "devops"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/xo5V9g9joFs?si=MfCnNwB59rrhXE07",
      github: "https://www.github.com",
      coverphoto: "/blogs/kelly-sikkema--1_RZL8BGBM-unsplash.jpg",
    },
    metadata: {
      likes: 195,
      comments: 30,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `This introduction to Kubernetes covers essential concepts for orchestrating containerized applications.`,
      keypoints: [
        "What is Kubernetes?",
        "Understanding pods, nodes, and clusters.",
        "Deployment configurations.",
        "Scaling and load balancing.",
      ],
      features: [
        "Automated deployment.",
        "Container orchestration.",
        "High availability.",
      ],
      libraries: ["kubectl", "Helm"],
      resources: ["Kubernetes docs", "Cloud-native landscape guide"],
      transcript: ``,
    },
  },
  {
    id: "1z2y3x4w5v6u7t8s9r0",
    title: "Full-stack App with MERN",
    description:
      "Build a complete application using MongoDB, Express, React, and Node.js.",
    tags: ["mern", "fullstack"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/iInUBOVeBCc?si=Rh35P8n0ZqBZMZiI",
      github: "https://www.github.com",
      coverphoto: "/blogs/lauren-mancke-aOC7TSLb1o8-unsplash.jpg",
    },
    metadata: {
      likes: 350,
      comments: 60,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `This guide walks through building a full-stack application using the MERN stack.`,
      keypoints: [
        "Setting up a React frontend.",
        "Creating a REST API with Express and Node.js.",
        "Integrating MongoDB.",
        "Deploying the MERN app.",
      ],
      features: [
        "Full-stack architecture.",
        "Seamless front-to-back communication.",
        "Responsive design.",
      ],
      libraries: ["React", "Express", "Mongoose"],
      resources: ["MERN docs", "React Redux integration"],
      transcript: ``,
    },
  },
  {
    id: "abcd1234efgh5678ijkl",
    title: "Modern CSS Techniques",
    description: "Enhance your web designs with modern CSS.",
    tags: ["css", "frontend"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/FtaQSdrl7YA?si=zZ9hH5F9indamJoW",
      github: "https://www.github.com",
      coverphoto: "/blogs/paul-esch-laurent-oZMUrWFHOB4-unspla.jpg",
    },
    metadata: {
      likes: 285,
      comments: 20,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `Learn how to use the latest CSS features to create visually stunning designs.`,
      keypoints: [
        "CSS Grid and Flexbox layouts.",
        "Variable and custom properties.",
        "CSS animations.",
        "Responsive design techniques.",
      ],
      features: [
        "Mobile-first design.",
        "Smooth animations.",
        "Custom theming.",
      ],
      libraries: ["Bootstrap", "Tailwind CSS"],
      resources: ["MDN CSS docs", "CanIUse.com"],
      transcript: ``,
    },
  },
  {
    id: "mnop9876qrst5432uvwx",
    title: "Intro to TypeScript",
    description:
      "Learn the basics of TypeScript for scalable JavaScript development.",
    tags: ["typescript", "javascript"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/IXifQ8mX8DE?si=xy4kbqEdoUDrGLTo",
      github: "https://www.github.com",
      coverphoto: "/blogs/paul-esch-laurent-oZMUrWFHOB4-unspla.jpg",
    },
    metadata: {
      likes: 310,
      comments: 50,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `Get started with TypeScript to write safer and more maintainable code.`,
      keypoints: [
        "Why TypeScript?",
        "Defining types and interfaces.",
        "Working with classes and generics.",
        "TypeScript tooling and debugging.",
      ],
      features: [
        "Static typing.",
        "Improved code readability.",
        "Enhanced tooling support.",
      ],
      libraries: ["TypeScript", "TSC"],
      resources: ["TypeScript docs", "TypeScript playground"],
      transcript: ``,
    },
  },
  {
    id: "zxy123uvw456rst789abc",
    title: "Understanding GraphQL",
    description: "Learn how to query APIs using GraphQL.",
    tags: ["graphql", "api"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/EXDkgjU8DDU?si=CroAPSWATtGPJ8TT",
      github: "https://www.github.com",
      coverphoto: "/blogs/paul-esch-laurent-oZMUrWFHOB4-unspla.jpg",
    },
    metadata: {
      likes: 200,
      comments: 35,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `Learn how GraphQL can be used to query data from APIs efficiently.`,
      keypoints: [
        "What is GraphQL?",
        "Setting up a GraphQL server.",
        "Writing queries and mutations.",
        "Using GraphQL with React.",
      ],
      features: [
        "Flexible data fetching.",
        "Real-time subscriptions.",
        "Reduced over-fetching.",
      ],
      libraries: ["Apollo", "GraphQL.js"],
      resources: ["GraphQL docs", "Apollo Client guide"],
      transcript: ``,
    },
  },
  {
    id: "456def123abc789ghi012",
    title: "Advanced Node.js",
    description: "Take your Node.js skills to the next level.",
    tags: ["nodejs", "backend"],
    links: {
      project: "",
      youtube: "https://www.youtube.com/embed/WPvGqX-TXP0?si=2dV7BS8J1BIoNdks",
      github: "https://www.github.com",
      coverphoto: "/blogs/paul-esch-laurent-oZMUrWFHOB4-unspla.jpg",
    },
    metadata: {
      likes: 260,
      comments: 40,
      published: "2024-12-09T14:54:35.631Z",
    },
    content: {
      overview: `Delve deeper into Node.js to create scalable and performant backend applications.`,
      keypoints: [
        "Event loop and async programming.",
        "Streams and buffers.",
        "Building scalable architectures.",
        "Using Worker Threads.",
      ],
      features: [
        "Asynchronous processing.",
        "Efficient I/O handling.",
        "Microservices support.",
      ],
      libraries: ["Node.js", "Cluster module"],
      resources: ["Node.js docs", "Event Loop deep dive"],
      transcript: ``,
    },
  },
];
